function assertValue<T>(value: T | undefined, errorMessage: string): T {
  if (value === undefined) {
    throw new Error(errorMessage);
  }
  return value;
}

// Sanity inlines process.env.SANITY_STUDIO_* into the browser bundle at build time.
// Values come from sanity/.env (generated by scripts/setup-sanity-env.js).
export const projectId = assertValue(
  process.env.SANITY_STUDIO_PROJECT_ID,
  'Missing Sanity project ID. Set NEXT_PUBLIC_SANITY_PROJECT_ID in .env.local and run: node scripts/setup-sanity-env.js'
);

export const dataset =
  process.env.SANITY_STUDIO_DATASET || 'production';
