// Sanity inlines process.env.SANITY_STUDIO_* into the browser bundle at build time.
// Values come from sanity/.env (generated by scripts/setup-sanity-env.js).
export const projectId = process.env.SANITY_STUDIO_PROJECT_ID;

export const dataset = process.env.SANITY_STUDIO_DATASET || 'production';

if (!projectId) {
  throw new Error(
    'Missing Sanity project ID. Set NEXT_PUBLIC_SANITY_PROJECT_ID in .env.local and run: node scripts/setup-sanity-env.js'
  );
}
